# Generated by Django 2.2.12 on 2020-08-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
