# Generated by Django 2.2.12 on 2020-08-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200806_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categorys',
        ),
    ]
