# Generated by Django 2.2.12 on 2020-08-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_article_categorys'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
