# Generated by Django 2.2.12 on 2020-08-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categorys',
            field=models.ManyToManyField(to='articles.Category'),
        ),
    ]
