# Generated by Django 2.2.12 on 2020-08-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_categorys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categorys',
        ),
        migrations.AddField(
            model_name='category',
            name='articles',
            field=models.ManyToManyField(to='articles.Article'),
        ),
    ]
