# Generated by Django 2.2.12 on 2020-08-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200806_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, to='articles.Category'),
        ),
    ]
