# Generated by Django 2.2.12 on 2020-08-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200806_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='section_one',
        ),
        migrations.AddField(
            model_name='article',
            name='section_three',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='section_two',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='thumb_one',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='article',
            name='thumb_three',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='article',
            name='thumb_two',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
